package first;
//Processing data generated by vissim
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.InputStream;
import java.io.PrintWriter;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class getjunzhi {

	static int count1=0; 
	public static void getNewJunzhi(String path,int n)throws Exception{
		String time;
		File excelFile = new File(path);
		XSSFWorkbook wb = null;
        
        wb = new XSSFWorkbook(new FileInputStream(excelFile));
    
    int numberOfSheets = wb.getNumberOfSheets();

    XSSFSheet s1=wb.getSheetAt(0);
    int first=s1.getFirstRowNum();
    int last=s1.getLastRowNum();
    double num=0;
    int count=0;
    double junzhi=0;
    
    for(int j=n;j<last;j++){
    	Row message=s1.getRow(j);
    	//if(!"".equals(message))
    	Cell cell0=message.getCell(0);//时间
    	
    	time=cell0.getStringCellValue();
    	String[] str=time.split(";");
    	num=num+Double.parseDouble(str[3]);
    	count++;
    	System.out.println(cell0);
    	
	}
    
    junzhi=num/count;
    System.out.println("均值为："+junzhi);
	}
	public static void getjunzhi(String path,int n,int flow,int laneNum,int time,double ratio)throws Exception{
		
		File f1=new File("D:\\sinc_test");//写文件
		FileWriter fw = new FileWriter(f1, true);
		 File f=new File(path);
		 InputStream intput=null;
		 intput=new FileInputStream(f);
		 byte b[]=new byte[(int)f.length()];
		 int len=intput.read(b);
		 String sss=new String(b);
		 intput.close();
		 System.out.println(sss);
		 int num1=0;//标记第几行
		 int num2=0;//标记第几个；
		 byte number[]=new byte[20];
		 //number=null;//暂存数据
		 int number1=0;//暂存数据指针
		 int shuju[]=new int[100];//存储数据数组
		 int shuju1=0;//数据个数指针
		 
		 for(int i=0;i<len;i++){
			 
			 if(b[i]=='\n'){
				 num1++;
			 }
			 if(num1>=n){
				// System.out.println(125);
				 //System.out.println(b[i]);
				 if(b[i]==';'){
					
					 num2++;
					 //System.out.println(num2);
				 }
				 if(b[i]=='\n'&&number1!=0){
					 //System.out.println(number);
					 String s=new String(number,0,number1);
					//System.out.println(s+"43");
					 shuju[shuju1]=Integer.parseInt(s);
					 num2=0;
					 number1=0;
					 shuju1++;
				 }
				 if(num2>2&&b[i]>='0'&&b[i]<='9'){
					
					 number[number1]=b[i];
					 number1++;
					 //System.out.println(new String(number)+"53");
				 }
			
			 }
		 }
		 double add=0;
		 for(int i=0;i<shuju1;i++){
			 add=add+shuju[i];
		 }
		 System.out.println("和为："+add+'\n'+"均值是："+add/shuju1);
		 PrintWriter pw = new PrintWriter(fw);
		 pw.print(Integer.toString(flow)+" "+Integer.toString(laneNum)+" "+Integer.toString(time)+" "+Double.toString(ratio)+" "+Double.toString(add/shuju1));pw.println(" ");
		 pw.flush();
	} 
	public static void main(String[] args) throws Exception{
		//  地址    行数      流量      输入车道数       时间      输入比
		getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally.mes",50,200,10,300,0.233);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,19,275,0.2968);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,18,275,0.2812);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,17,275,0.2656);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,16,275,0.25);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,15,275,0.2343);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,14,275,0.2188);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,13,275,0.2031);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,12,275,0.1875);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,11,275,0.1719);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,10,275,0.1563);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,9,275,0.1406);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,8,275,0.125);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,7,275,0.163);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,6,275,0.1094);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,5,275,0.0938);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,4,275,0.0625);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,3,275,0.0469);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,2,275,0.0313);
		//getjunzhi("D:\\vissim4.3 破解版\\Exe\\finally2.mes",97,180,1,275,0.0156);
		//getNewJunzhi("D:\\vissim4.3 破解版\\Exe\\finally.mes",50);
		//count1++;
		//System.out.print(count1);
        
	}

}




